controller_manager:
  ros__parameters:
    update_rate: 100
    leg_controller:
      type: forward_command_controller/ForwardCommandController

leg_controller:
  ros__parameters:
    joints:
      - FL_hip_joint
      - FL_joint
      - FR_hip_joint
      - FR_joint
      - BL_hip_joint
      - BL_joint
      - BR_hip_joint
      - BR_joint
    interface_name: position
    gains:
      FL_hip_joint: {p: 1000.0, i: 10.0, d: 80.0}
      FL_joint:     {p: 1500.0, i: 20.0, d: 100.0}
      FR_hip_joint: {p: 1000.0, i: 10.0, d: 80.0}
      FR_joint:     {p: 1500.0, i: 20.0, d: 100.0}
      BL_hip_joint: {p: 1000.0, i: 10.0, d: 80.0}
      BL_joint:     {p: 1500.0, i: 20.0, d: 100.0}
      BR_hip_joint: {p: 1000.0, i: 10.0, d: 80.0}
      BR_joint:     {p: 1500.0, i: 20.0, d: 100.0}
